### ISSUE TITLE
Issue with Heroku

### ISSUE THREAD

**Issue by zack-overflow** [layuplist/layup-list#65]
The main LL site is down. Going to https://www.layuplist.com/ returns a 503 error and redirects to a page saying there is an error with the Heroku application.

![Screen Shot 2022-12-11 at 4 58 19 PM](https://user-images.githubusercontent.com/51934587/206940445-10203a1e-8538-4417-9d2f-a3c0c704ae68.png)

**Comment by zack-overflow** [comment]
This is likely due to [Heroku shutting down its free tier](https://blog.heroku.com/next-chapter) starting on Nov 28, 2022. Posts on social media about LL being down go back at least a week.

**Comment by zack-overflow** [comment]
Heroku's free tier was very generous, so replacing it may require multiple hosting options. [Render](https://render.com/pricing) has an intriguing free tier, as does [Cyclic](https://www.cyclic.sh/pricing).

**Comment by jaismith** [comment]
Hey Zack, thanks for posting these issues! The team was offline over the weekend and heroku deleted the redis db linked to the site. Just restored it and should be back online :).
